#!/bin/bash
FILE_PATH=$1
FUEL_REQUIREMENT_TOTAL=0
FUEL_CALCULATED=0

while read c; do
  echo "$c"
  FUEL_CALCULATED=$((c/3))
  FUEL_CALCULATED=$((FUEL_CALCULATED-2))
  echo FUEL_CALCULATED: $FUEL_CALCULATED
  FUEL_REQUIREMENT_TOTAL=$(( FUEL_REQUIREMENT_TOTAL+FUEL_CALCULATED ))
done < "$FILE_PATH"

echo Fuel Requirement Total: $FUEL_REQUIREMENT_TOTAL