#!/bin/bash
FILE_PATH=$1
FUEL_REQUIREMENT_TOTAL=0
FUEL_CALCULATED=0

while read -n 1 c; do
  echo "$c"
  $FUEL_REQUIREMENT_TOTAL = $c / 3 - 2
  #FUEL_REQUIREMENT_TOTAL=$(( FUEL_REQUIREMENT_TOTAL+FUEL_CALCULATED ))
done < "$FILE_PATH"

echo $FUEL_REQUIREMENT_TOTAL
